---
# variables:
# gitlab: gitlab to link to
# token: registration token
- include: install_runner.yml
- hosts: "{{ci_runners|default('all')}}"
  vars:
    ci_lxc: false
  tasks:
    - template:
        dest: /srv/projects/gitlabrunner/pillar/init.sls
        src: ../templates/install_pillar
        mode: "0600"
        force: true
    - shell: |
        set -ex
        cat /srv/projects/gitlabrunner/pillar/init.sls
        cd /srv/projects/gitlabrunner/project
        salt-call --retcode-passthrough mc_project.deploy gitlabrunner only=install,fixperms

