---
- hosts: "{{provision_node}}"
  tasks:
    - name: pillar
      copy:
        dest: /srv/makina-states/pillar/pillar.d/redis.sls
        content: |
          ---
          makina-states.services.db.redis.password: redis
          makina-states.services.db.redis.redis.bind: 127.0.0.1
      tags: redis_install
    - name: re config redis - first time may fail
      saltcall:
        function: state.sls
        args: "makina-states.services.db.redis"
      register: redis_install_1
      tags: redis_install
    - name: re config redis - first time may fail
      saltcall:
        function: state.sls
        args: "makina-states.services.db.redis"
      register: redis_install_2
      when: "{{redis_install_1.result.retcode != 0}}"
      tags: redis_install
