---
# Run project setup
- include: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/vars.yml"
  vars: {inc_node: "{{test_node}}"}
- hosts: "{{test_node}}"
  tasks:
    - name: build project
      shell: |
        salt-call -lall --retcode-passthrough \
          mc_project.deploy {{ms_project_name}} only=install,fixperms
      when: "{{TEST_USE_MAKINASTATES}}"
      tags: project_setup,project_setup_ms
